### ISSUE TITLE
Find out path to calibre library

### ISSUE THREAD

**Issue by strarsis** [Xyfir/node-calibre#6]
After a book has been added to calibre (calibredb command), for further conversion using calibre-convert command, the absolute path to imported book has to be specified.
The default calibre library path should be used/assumed, 
how can it be determined from the calibre CLI tools?

Alternatively this wrapper could offer a method/other means for getting the library path –
or automatically converting relative paths to absolute paths inside the library path.

**Comment by MrXyfir** [comment]
You can get the full path using the [calibredb list](https://manual.calibre-ebook.com/generated/en/calibredb.html#list) command. You can get the path(s) from the `formats` field. If you just want to load one specific book from the list command you can use the `search` option with `id:123` where 123 is obviously the book's actual id.

I'm not entirely sure what you mean in the second part. node-calibre assumes that you'll pass the path of the library that you want to work with.

**Comment by strarsis** [comment]
I need the absolute path for `calibre-convert` because that tool doesn't seem to know about libraries (or IDs) at all, it just expects input and output file paths.

**Comment by MrXyfir** [comment]
Yeah, currently you'll need to get the absolute file paths manually via the `calibredb list` command with the appropriate fields (`formats`, `cover`, etc) depending on what files you need.

Maybe in the future node-calibre could add additional functionality on top of Calibre but for now I just want to properly wrap all of Calibre's commands. Since Calibre doesn't have any CLI to do this directly (unless I'm not aware of it), I'll close this for now.
