### ISSUE TITLE
WSL/Windows support

### ISSUE THREAD

**Issue by strarsis** [Xyfir/node-calibre#7]
In WSL (Bash on Windows) shell, the binaries/commands can't be found by node-calibre (e.g. 'calibredb').
````
(node:9474) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: calibredb list --library-path ""
/bin/sh: 1: calibredb: not found
(node:9474) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

**Comment by MrXyfir** [comment]
Are you sure Calibre is installed in the actual subsystem? I don't think it'll work if it's installed on Windows, you must install it within the subsystem (which is what I do, and it works). I recommend installing it directly from Calibre's site instead of from Ubuntu's package manager so that you get the latest version.

**Comment by MrXyfir** [comment]
Ah, well in that case, see the third bullet point at https://github.com/Xyfir/node-calibre#important-notes

**Comment by strarsis** [comment]
@MrXyfir: I see, folder with calibre(.exe) binary should be added to PATH.
On Windows systems the PATH is not used like on *nix systems. An autodiscovery feature would be nice – 
at least trying out the default Calibre installation path (C:\Program Files\Calibre2) by default.
